import os
from flask import Flask, render_template,request
import sys
import logging
from allennlp.predictors.predictor import Predictor
import allennlp_models.rc
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bidaf-elmo-model-2020.03.19.tar.gz")
ar = "Aishwarya loves an active and friendly person.A perfect day for her would be when all her tasks are completed perfectly.Aishwarya has a fear of heights.Aishwarya loves her phone and likes to listen to music by herself.Aishwarya wants to go to Wayanad the most.One thing you may not know is that Aishwarya can get a little sensitive. Aishwarya does not like to eat one thing for the rest of her life. No book has impacted her currently. Her best present ever was a pen.Japanese is the foreign language Aishwarya wants to master. Her all-time favorite dessert is Gulab Jamun. Aishwarya aspires to be a developer.Her style is very calm. If Aishwarya was an animal, Aishwarya would be an eagle.Her dream job is in Google. Errors,Noise and Idleness are 3 things that stress her out. Favorite color is blue. Aishwarya like dosa for breakfast. Aishwarya loves the hibiscus flower."
gp = "Gokul Prakash loves a kind and caring person. Gokul Prakash perfect day would be a holiday without any work. Gokul Prakash does not fear anything. Gokul Prakash favorite things are his laptop and phone. Gokul Prakash is secretive of his favorite thing to do alone.Gokul Prakash wants to travel to Ooty and Kodaikanal the most.One thing you may not know about him is that he's dangerous.Gokul Prakash would like to eat Maggi for the rest of his life.Harry Potter is the book that impacted him the most.Gokul Prakash best present ever was a Rubik's Cube. The foreign language Gokul Prakash wants to master is English.Gokul Prakash all-time favorite dessert is Brownie.Gokul Prakash wants to take the IT Professional Career Path.Gokul Prakash personal style is Cool.If Gokul Prakash was an animal he would be a Lion.Gokul Prakash dream job would be being a Developer.Slow Internet, Low Battery and No new movies are 3 things that stress him out.Gokul Prakash favorite color is Blue.Gokul Prakash usually has Dosa for breakfast.Gokul Prakash favorite flower is the Rose."
ra = "Rakshmitha loves a trustful and caring person.Her perfect day would be the day she came into the world.Her biggest fear is the unseen.Her favorite thing is her teddy bear. Rakshmitha loves to do art by herself.Rakshmitha wants to travel to the Arctic the most.Rakshmitha does not read books. Rakshmitha would like to eat Naan and butter chicken for the rest of her life.Her best present is a ring.A foreign language she is looking to master is Japanese.Her all-time favorite dessert is Vanilla ice-cream with gulab jamun.Her future career path would be in IT Research.Her style can be described as Bold, Enthusiastic,Optimistic and Hardworking.If she was an animal she would like to be a swan.Rakshmitha does not have anything that anyone else does not know about her.Her dream job in in IT Research.Not being punctual, being irresponsible and narrow-mindedness are the 3 things that stress her out. Her favorite color is Black. Her breakfast is usually Cornflakes, Banana and Apple with Hot Milk. Her favorite plant or flower is Rose."
vv = "Vaishnavi loves a dedicated, caring person and one with good communication.Vaishnavi perfect day is when all her work is completed.Vaishnavi biggest fear is herself.Vaishnavi favorite thing ever is herself.Vaishnavi favorite things to do by herself is to listen to music.Vaishnavi loves to travel to the beach the most.One thing you may not know is that she speaks Hindi.Nancy Drew is a book that impacted her the most.The best present she ever got was a purse.German is a foreign language she wants to master.Vaishnavi all-time dessert is Ice cream.Vaishnavi future career path is CSE.Vaishnavi personal style can be described as Talkative.If she were an animal she would be a Dolphin. Vaishnavi absolute dream job would be at VVBN.Exams is one things that stresses her out.Blue is her favorite color.Vaishnavi loves to have Dosa for breakfast. Vaishnavi favorite flower is Rose."
ad = "Augustin Dennis loves a person who shares.His perfect day would be one without any hard feelings.His biggest fear would be losing his loved ones.His favorite things that he owns are his family and friends.Augustin Dennis loves Bike Rides by himself.Augustin Dennis always wants to travel to Australia.One thing you may not know is that he likes to eat a lot.Augustin Dennis would like to have Chicken for the rest of his life.Brief Answer to the Big Questions by Stephen Hawking is the book that impacted him the most.Augustin Dennis best present ever was a bike. German is one of the foreign languages he wants to master.Augustin Dennis all time favorite dessert is Ice Cream. Augustin Dennis future career path would be a business person.Augustin Dennis personal style is staying unique. Augustin Dennis dream job is CEO of his own company.Losing loved ones, Being Rejected and Being Avoided are the 3 things that stresses him out.Augustin Dennis favorite color is Blue.Augustin Dennis breakfast is usually Bread Omlet or Milk. Augustin Dennis favorite plant is the Touch Me Not."
ya = "Yagan Arun loves a person who is Supporting, Cooperative, Passionate and Like minded as himself.Yagan Arun perfect day would be Even if he could'nt solve a problem at the end of the day he learnt something.Yagan Arun biggest fear is Public Speaking.Yagan Arun favorite thing that he owns is his failures because he always gives his best solution to the problem. Yagan Arun favorite thing to do alone is Game development and develop games based on that.Yagan Arun wants to travel to Canada the most.One thing you may not know about him is his possessiveness.One thing he would like to eat for the rest of his life will be ice cream.Yagan Arun never reads books.Yagan Arun best present ever is a iPhone 11.A foreign language he wants to master is English.Yagan Arun all time dessert is Ice Cream.Yagan Arun future careeer path is in the Gaming industry.Yagan Arun personal style can be described as professional.Yagan Arun dream job is to start his own gaming company.Deadlines, being stuck at something and when someone questions him are the 3 things that stress him out.Yagan Arun favorite color is Black.Yagan Arun breakfast is usually Idly or Dosa in some cases. Yagan Arun favorite flower is Rose."
kv = "Katikala Vyshnavi loves a smart person.  perfect day would be when Katikala Vyshnavi learnt something new. biggest fear is not completing work within the deadline. favorite thing Katikala Vyshnavi owns is her laptop. favorite thing to do alone is to listen to songs in high volume.Katikala Vyshnavi wants to travel to Dubai the most.One thing you may not know about her is that Katikala Vyshnavi is very focused.One thing Katikala Vyshnavi would like to eat for the rest of her life would be Chicken Biriyani.Katikala Vyshnavi does not read books.The best present Katikala Vyshnavi ever received was a Teddy Bear.Foreign languages Katikala Vyshnavi would like to learn would be English,Chinese and Japanese. all time favorite desserts are Chocolate and Turkish Delight. style can be described as Casual and Attractive.If Katikala Vyshnavi were an animal Katikala Vyshnavi would be an Eagle. absolute dream job is a Full stack web developer. careeer path is Full stack developer.Learning from mistakes, improving vocabulary and time management are 3 things that stress her out.Dosa is her usual breakfast.  favorite flower is Jasmine."
sf = "Sameena Fathima loves a friendly and loyal person. Sameen Fathima perfect day would be spending a day with Sameen Fathima family.Sameen Fathima biggest fear is losing Sameen Fathima loved ones.Sameen Fathima favorite thing ever is Sameen Fathima phone.Sameen Fathima favorite thing to do is watching comedy shows.She would like to travel to Paris the most. One thing most people don't know about Sameen Fathima is Sameen Fathima sense of humour.If she could eat one thing for the rest of Sameen Fathima life, it would be Biryani.Wings of Fire is the book that has impacted Sameen Fathima the most.The best present that she ever got was a laptop.French is a foreign language she would want to master.Ice cream is Sameen Fathima all time favorite dessert.Software developer is a path she wants to take in the future.Sameen Fathima personal style can be described as simple.If she were an animal she would be a lion.Sameen Fathima absolute dream job is a Software Developer.Fight with a friend,no wifi and not finishing a task on time are the 3 things that stress Sameen Fathima out.Red is Sameen Fathima favorite color.Dosa is Sameen Fathima usual breakfast.Rose is Sameen Fathima favorite flower."
k = "Karthik loves a person who has these qualities:Honesty,Integrity,Optimism,Trust,Courage and Kindness.Karthik perfect day can be described as follows:After a nice sleep, doing things that bring him happiness and peace.Karthik biggest fear is the fear of being judged.Karthik favorite things to do alone include playing Keyboard and Practising Card magic Tricks.USA is a country that he would love to travel the most.One thing you may not know about him is that he's gentle.If he could eat one thing for the rest of Karthik life it would be majorly non-veg or prawn dishes.He hasn't read any other books apart from study books.The best present he ever got was a PS3.A foreign language that he would like to learn is English.Karthik all time favourite desserts include:Gulab Jamun, Kaju roll and Choco Truffle Cake.A career path he is looking to pursue Web and Mobile App developer and is also interested in Civil Service.Karthik personal style can be described as Calm and composed with determination and eager to learn new skills.If he were an animal he would be a Lion.Karthik absolute dream job would be to be a CEO of a well reputed company.Death of loved ones,Emotional problems and Unrealistic expectations are 3 things that stress him out.Karthik favorite color is Black.Idli is Karthik usual breakfast.Rose is Karthik favorite flower."

d={'Aishwarya':ar,
    'Gokul Prakash':gp,
    'Rakshmitha':ra,
    'Vaishnavi':vv,
    'Augustin Dennis':ad,
    'Yagan Arun':ya,
    'Katikala Vyshnavi':kv,
    'Sameena Fathima':sf,
    'Karthik':k}

app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'XYZ')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/qa')
def qaallen():
    return render_template('login.html')

@app.route('/answer', methods=['POST'])
def answer():
    q = str(request.form['question'])
    p = str(request.form['person'])

    l=predictor.predict(passage=d[p] , question=q)

    return render_template('features.html',answer=l['best_span_str'])